// 内置词书数据：单词背诵功能内置的几本高频词书。
// 每本词书关联到某个备考场景，用户一键"加入背诵"后写入 cards 表（打 vocab 标签）。
// 词条均为精选真实词汇，含音标 / 中文释义 / 例句，可直接背诵。

export interface WordEntry {
  word: string;
  phonetic?: string;
  meaning: string;
  example: string;
}

export interface WordBook {
  key: string;
  name: string;
  scenario: string; // 关联备考场景（与 scenarios.ts 对齐，用于 UI 提示）
  desc: string;
  words: WordEntry[];
}

function w(word: string, phonetic: string, meaning: string, example: string): WordEntry {
  return { word, phonetic, meaning, example };
}

// 高中核心词（高考 3500 词精选高频，A–C 段，40 词）
const GAOKAO_A: WordEntry[] = [
  w("abandon", "/əˈbændən/", "v. 放弃，抛弃", "He had to abandon his plan."),
  w("ability", "/əˈbɪləti/", "n. 能力，才能", "She has the ability to solve problems."),
  w("absent", "/ˈæbsənt/", "adj. 缺席的", "He was absent from school yesterday."),
  w("absorb", "/əbˈzɔːb/", "v. 吸收，吸引", "Plants absorb sunlight through leaves."),
  w("abstract", "/ˈæbstrækt/", "adj. 抽象的", "This idea is too abstract for kids."),
  w("academic", "/ˌækəˈdemɪk/", "adj. 学术的", "She has a strong academic background."),
  w("accept", "/əkˈsept/", "v. 接受", "I accept your kind invitation."),
  w("access", "/ˈækses/", "n. 通道，使用权", "Students have access to the library."),
  w("accident", "/ˈæksɪdənt/", "n. 事故，意外", "A car accident happened on the road."),
  w("accompany", "/əˈkʌmpəni/", "v. 陪伴，伴随", "She accompanied her friend to the hospital."),
  w("account", "/əˈkaʊnt/", "n. 账户，描述", "Please open a bank account."),
  w("achieve", "/əˈtʃiːv/", "v. 实现，达到", "He achieved his dream through hard work."),
  w("acquire", "/əˈkwaɪə(r)/", "v. 获得，习得", "Children acquire knowledge quickly."),
  w("active", "/ˈæktɪv/", "adj. 积极的，活跃的", "She is active in class activities."),
  w("actual", "/ˈæktʃuəl/", "adj. 实际的，真实的", "The actual cost was higher than expected."),
  w("adapt", "/əˈdæpt/", "v. 适应，改编", "He adapted to the new school soon."),
  w("adequate", "/ˈædɪkwət/", "adj. 足够的，恰当的", "We need adequate food and water."),
  w("adjust", "/əˈdʒʌst/", "v. 调整，适应", "Please adjust your seat to fit you."),
  w("admire", "/ədˈmaɪə(r)/", "v. 钦佩，欣赏", "I admire her courage very much."),
  w("admit", "/ədˈmɪt/", "v. 承认，准许进入", "He admitted his small mistake."),
  w("adopt", "/əˈdɒpt/", "v. 采纳，收养", "They adopted a healthy lifestyle."),
  w("advantage", "/ədˈvɑːntɪdʒ/", "n. 优势，好处", "Practice gives you an advantage."),
  w("advertise", "/ˈædvətaɪz/", "v. 做广告，宣传", "They advertised the product online."),
  w("affect", "/əˈfekt/", "v. 影响，感动", "Rain affects the harvest every year."),
  w("afford", "/əˈfɔːd/", "v. 负担得起", "We cannot afford a new car now."),
  w("afraid", "/əˈfreɪd/", "adj. 害怕的", "Do not be afraid of making errors."),
  w("agree", "/əˈɡriː/", "v. 同意，一致", "I agree with your opinion."),
  w("ahead", "/əˈhed/", "adv. 在前面，向前", "Go ahead and start the work."),
  w("aim", "/eɪm/", "v. 瞄准，旨在", "We aim to win the competition."),
  w("alarm", "/əˈlɑːm/", "n. 警报，闹钟", "The fire alarm rang suddenly."),
  w("alive", "/əˈlaɪv/", "adj. 活着的", "The little fish is still alive."),
  w("allow", "/əˈlaʊ/", "v. 允许，准许", "Allow me to help you with this."),
  w("alone", "/əˈləʊn/", "adj. 独自的", "She lives alone in the city."),
  w("aloud", "/əˈlaʊd/", "adv. 大声地", "Please read the text aloud."),
  w("amazing", "/əˈmeɪzɪŋ/", "adj. 令人惊奇的", "What an amazing view it is!"),
  w("ambitious", "/æmˈbɪʃəs/", "adj. 有雄心的", "He is ambitious about his future."),
  w("analyze", "/ˈænəlaɪz/", "v. 分析，分解", "Let us analyze the problem first."),
  w("ancient", "/ˈeɪnʃənt/", "adj. 古代的，古老的", "Ancient history is fascinating."),
  w("announce", "/əˈnaʊns/", "v. 宣布，通告", "They announced the final result."),
  w("anxious", "/ˈæŋkʃəs/", "adj. 焦虑的，渴望的", "She is anxious about the exam."),
];

// 高中核心词（续，D–C 段，40 词）
const GAOKAO_B: WordEntry[] = [
  w("appear", "/əˈpɪə(r)/", "v. 出现，显得", "Stars appear at night in the sky."),
  w("appreciate", "/əˈpriːʃieɪt/", "v. 欣赏，感激", "I appreciate your kind help."),
  w("approach", "/əˈprəʊtʃ/", "v. 接近 n. 方法", "We need a new approach to study."),
  w("approve", "/əˈpruːv/", "v. 批准，赞成", "The teacher approved our plan."),
  w("argue", "/ˈɑːɡjuː/", "v. 争论，主张", "They argued about the answer."),
  w("arrange", "/əˈreɪndʒ/", "v. 安排，整理", "Please arrange a meeting for us."),
  w("arrest", "/əˈrest/", "v. 逮捕，拘留", "The police arrested the thief."),
  w("arrive", "/əˈraɪv/", "v. 到达，抵达", "We arrived at school on time."),
  w("ashamed", "/əˈʃeɪmd/", "adj. 羞愧的", "He felt ashamed of his lie."),
  w("assist", "/əˈsɪst/", "v. 协助，帮助", "Please assist the teacher after class."),
  w("assume", "/əˈsjuːm/", "v. 假定，承担", "Let us assume the theory is right."),
  w("astonish", "/əˈstɒnɪʃ/", "v. 使惊讶", "The news astonished all of us."),
  w("attach", "/əˈtætʃ/", "v. 附上，系", "Please attach a photo to the email."),
  w("attack", "/əˈtæk/", "v. 攻击，袭击", "He attacked the difficult problem."),
  w("attract", "/əˈtrækt/", "v. 吸引，引起", "The show attracts many visitors."),
  w("average", "/ˈævərɪdʒ/", "adj. 平均的", "The average score is eighty-five."),
  w("avoid", "/əˈvɔɪd/", "v. 避免，回避", "Try to avoid making the same error."),
  w("awake", "/əˈweɪk/", "adj. 醒着的", "The baby is still awake now."),
  w("aware", "/əˈweə(r)/", "adj. 意识到的", "Be aware of the new traffic rules."),
  w("belief", "/bɪˈliːf/", "n. 信念，相信", "He has a strong belief in himself."),
  w("belong", "/bɪˈlɒŋ/", "v. 属于", "This book belongs to my brother."),
  w("beneficial", "/ˌbenɪˈfɪʃl/", "adj. 有益的", "Reading is beneficial to us."),
  w("blame", "/bleɪm/", "v. 责备，归咎", "Do not blame him for the mistake."),
  w("brave", "/breɪv/", "adj. 勇敢的", "He is a brave and honest boy."),
  w("brief", "/briːf/", "adj. 简短的", "Give a brief answer, please."),
  w("bright", "/braɪt/", "adj. 明亮的，聪明的", "She has a bright smile."),
  w("broad", "/brɔːd/", "adj. 宽的，广阔的", "The road is broad and clean."),
  w("burden", "/ˈbɜːdn/", "n. 负担，重负", "Too much homework is a burden."),
  w("calm", "/kɑːm/", "adj. 平静的，冷静的", "Stay calm before the exam."),
  w("capable", "/ˈkeɪpəbl/", "adj. 有能力的", "She is capable of the task."),
  w("career", "/kəˈrɪə(r)/", "n. 职业，事业", "He chose a teaching career."),
  w("cautious", "/ˈkɔːʃəs/", "adj. 谨慎的", "Be cautious when crossing the road."),
  w("challenge", "/ˈtʃælɪndʒ/", "n. 挑战", "Life is full of challenges."),
  w("character", "/ˈkærəktə(r)/", "n. 性格，角色", "He has a strong character."),
  w("circumstance", "/ˈsɜːkəmstɑːns/", "n. 环境，情况", "Under no circumstance should you give up."),
  w("classify", "/ˈklæsɪfaɪ/", "v. 分类，归类", "Classify the words by topic."),
  w("colleague", "/ˈkɒliːɡ/", "n. 同事", "My colleague is very kind."),
  w("comment", "/ˈkɒment/", "n. 评论，意见", "Leave a comment below the article."),
  w("compare", "/kəmˈpeə(r)/", "v. 比较，对比", "Compare the two pictures carefully."),
];

// 四级高频词（大学英语四级精选高频，60 词）
const CET4: WordEntry[] = [
  w("absence", "/ˈæbsəns/", "n. 缺席，缺乏", "His absence was noticed by all."),
  w("absorb", "/əbˈzɔːb/", "v. 吸收，吸引", "The paper absorbs ink quickly."),
  w("academic", "/ˌækəˈdemɪk/", "adj. 学术的", "Academic research takes time."),
  w("accept", "/əkˈsept/", "v. 接受，同意", "I accept your kind offer."),
  w("access", "/ˈækses/", "n. 通道，使用权", "Get access to the computer lab."),
  w("accident", "/ˈæksɪdənt/", "n. 事故，意外", "A traffic accident blocked the road."),
  w("accompany", "/əˈkʌmpəni/", "v. 陪伴，伴随", "Music accompanies the film well."),
  w("account", "/əˈkaʊnt/", "n. 账户，描述", "Please check your bank account."),
  w("achieve", "/əˈtʃiːv/", "v. 实现，达到", "He achieved great success at last."),
  w("acquire", "/əˈkwaɪə(r)/", "v. 获得，习得", "Acquire new skills every year."),
  w("adequate", "/ˈædɪkwət/", "adj. 足够的，恰当的", "Adequate sleep matters a lot."),
  w("adjust", "/əˈdʒʌst/", "v. 调整，适应", "Adjust the light before reading."),
  w("adopt", "/əˈdɒpt/", "v. 采纳，收养", "They adopted a new method."),
  w("advance", "/ədˈvɑːns/", "v. 推进 n. 进步", "Technology advances very fast."),
  w("adverse", "/ˈædvɜːs/", "adj. 不利的，相反的", "Adverse weather delayed the trip."),
  w("advise", "/ədˈvaɪz/", "v. 建议，劝告", "I advise you to rest more."),
  w("affect", "/əˈfekt/", "v. 影响，感动", "Noise affects our sleep quality."),
  w("afford", "/əˈfɔːd/", "v. 负担得起", "Can you afford the new phone?"),
  w("agency", "/ˈeɪdʒənsi/", "n. 机构，代理", "A travel agency helped us."),
  w("agenda", "/əˈdʒendə/", "n. 议程，日程", "The meeting agenda is full."),
  w("alert", "/əˈlɜːt/", "adj. 警觉的", "Stay alert when walking at night."),
  w("allocate", "/ˈæləkeɪt/", "v. 分配，拨出", "Allocate your time wisely."),
  w("alter", "/ˈɔːltə(r)/", "v. 改变，修改", "Alter the plan if needed."),
  w("ambitious", "/æmˈbɪʃəs/", "adj. 有野心的", "It is an ambitious project."),
  w("analyze", "/ˈænəlaɪz/", "v. 分析，分解", "Analyze the data with care."),
  w("ancestor", "/ˈænsestə(r)/", "n. 祖先，祖宗", "Honor your ancestors, please."),
  w("angle", "/ˈæŋɡl/", "n. 角度，视角", "View it from a new angle."),
  w("anniversary", "/ˌænɪˈvɜːsəri/", "n. 周年纪念", "Our anniversary is in May."),
  w("announce", "/əˈnaʊns/", "v. 宣布，通告", "They announced the winner."),
  w("annual", "/ˈænjuəl/", "adj. 每年的", "The annual meeting is in January."),
  w("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期，预料", "We anticipate some problems."),
  w("anxiety", "/æŋˈzaɪəti/", "n. 焦虑，渴望", "Exam anxiety is common."),
  w("appetite", "/ˈæpɪtaɪt/", "n. 食欲，胃口", "He has a good appetite today."),
  w("appliance", "/əˈplaɪəns/", "n. 器具，电器", "A kitchen appliance broke."),
  w("applicant", "/ˈæplɪkənt/", "n. 申请人", "The applicant waited politely."),
  w("appoint", "/əˈpɔɪnt/", "v. 任命，约定", "They appointed a new leader."),
  w("appreciate", "/əˈpriːʃieɪt/", "v. 欣赏，感激", "We appreciate the beautiful art."),
  w("approach", "/əˈprəʊtʃ/", "n. 方法，途径", "A new approach works better."),
  w("appropriate", "/əˈprəʊpriət/", "adj. 适当的", "Wear appropriate clothes."),
  w("approve", "/əˈpruːv/", "v. 批准，赞成", "The boss approved the request."),
  w("arbitrary", "/ˈɑːbɪtrəri/", "adj. 任意的，武断的", "It was an arbitrary choice."),
  w("argue", "/ˈɑːɡjuː/", "v. 争论，辩论", "Argue politely with facts."),
  w("arise", "/əˈraɪz/", "v. 出现，发生", "New problems arise each day."),
  w("arrange", "/əˈreɪndʒ/", "v. 安排，整理", "Arrange the trip in advance."),
  w("arrest", "/əˈrest/", "v. 逮捕，拘留", "Police arrest the suspect."),
  w("articulate", "/ɑːˈtɪkjuleɪt/", "adj. 口齿清晰的", "She is an articulate speaker."),
  w("aspect", "/ˈæspekt/", "n. 方面，层面", "Every aspect of life matters."),
  w("assess", "/əˈses/", "v. 评估，评定", "Assess the risk before acting."),
  w("assign", "/əˈsaɪn/", "v. 分配，指派", "The teacher assigns homework."),
  w("assist", "/əˈsɪst/", "v. 协助，帮助", "Assist the elderly, please."),
  w("associate", "/əˈsəʊʃieɪt/", "v. 联系，联想", "We associate red with danger."),
  w("assume", "/əˈsjuːm/", "v. 假定，承担", "Assume the best in people."),
  w("assure", "/əˈʃʊə(r)/", "v. 使确信，保证", "Assure them of their safety."),
  w("attach", "/əˈtætʃ/", "v. 附上，系", "Attach the file to the email."),
  w("attack", "/əˈtæk/", "v. 攻击，抨击", "Attack the problem directly."),
  w("attain", "/əˈteɪn/", "v. 达到，获得", "Attain your goal with effort."),
  w("attend", "/əˈtend/", "v. 参加，出席", "Attend the lecture on time."),
  w("attitude", "/ˈætɪtjuːd/", "n. 态度，看法", "Keep a positive attitude."),
  w("attribute", "/əˈtrɪbjuːt/", "v. 归因于", "Attribute success to hard work."),
  w("audience", "/ˈɔːdiəns/", "n. 观众，听众", "The audience applauded loudly."),
];

// 六级高频词（大学英语六级较难词汇，50 词）
const CET6: WordEntry[] = [
  w("abnormal", "/æbˈnɔːml/", "adj. 反常的，异常的", "His abnormal behavior worried us."),
  w("abolish", "/əˈbɒlɪʃ/", "v. 废除，废止", "They abolished the old rule."),
  w("absurd", "/əbˈsɜːd/", "adj. 荒谬的，荒唐的", "That idea sounds quite absurd."),
  w("abundance", "/əˈbʌndəns/", "n. 丰富，充裕", "The region has an abundance of water."),
  w("accelerate", "/əkˈseləreɪt/", "v. 加速，促进", "Accelerate the reform process."),
  w("accommodate", "/əˈkɒmədeɪt/", "v. 容纳，适应", "The hall accommodates five hundred."),
  w("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累，积聚", "Accumulate experience over time."),
  w("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认，确认", "He acknowledged his error openly."),
  w("acquaint", "/əˈkweɪnt/", "v. 使熟悉，使认识", "Acquaint yourself with the rules."),
  w("adjacent", "/əˈdʒeɪsnt/", "adj. 相邻的，邻近的", "The two rooms are adjacent."),
  w("advocate", "/ˈædvəkeɪt/", "v. 提倡，拥护", "They advocate a green lifestyle."),
  w("affection", "/əˈfekʃn/", "n. 喜爱，感情", "She shows affection to the child."),
  w("affiliate", "/əˈfɪlieɪt/", "v. 使隶属，使附属于", "The club affiliates with the school."),
  w("aggressive", "/əˈɡresɪv/", "adj. 好斗的，进取的", "An aggressive marketing plan."),
  w("align", "/əˈlaɪn/", "v. 对齐，使一致", "Align the text to the left."),
  w("allege", "/əˈledʒ/", "v. 声称，断言", "He alleged unfair treatment."),
  w("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模糊的，歧义的", "Give an ambiguous answer."),
  w("ample", "/ˈæmpl/", "adj. 充足的，宽敞的", "We have ample evidence now."),
  w("analogy", "/əˈnælədʒi/", "n. 类比，相似", "Use an analogy to explain it."),
  w("antique", "/ænˈtiːk/", "adj. 古老的 n. 古董", "An antique vase from the Ming."),
  w("apparatus", "/ˌæpəˈreɪtəs/", "n. 设备，器械", "Lab apparatus must be clean."),
  w("appendix", "/əˈpendɪks/", "n. 附录，阑尾", "See the appendix for details."),
  w("applaud", "/əˈplɔːd/", "v. 鼓掌，称赞", "The crowd applauded the actor."),
  w("appraisal", "/əˈpreɪzl/", "n. 评估，评价", "A yearly job appraisal."),
  w("apt", "/æpt/", "adj. 恰当的，聪明的", "An apt remark at the moment."),
  w("array", "/əˈreɪ/", "n. 阵列，一系列", "An array of choices appeared."),
  w("ascend", "/əˈsend/", "v. 上升，攀登", "Ascend the mountain at dawn."),
  w("ascribe", "/əˈskraɪb/", "v. 归因于，归咎于", "Ascribe the change to the policy."),
  w("assert", "/əˈsɜːt/", "v. 断言，坚持", "Assert your legal rights."),
  w("asset", "/ˈæset/", "n. 资产，优点", "Honesty is a real asset."),
  w("assimilate", "/əˈsɪməleɪt/", "v. 吸收，同化", "Assimilate knowledge step by step."),
  w("assurance", "/əˈʃʊərəns/", "n. 保证，确信", "He gave us his assurance."),
  w("astonish", "/əˈstɒnɪʃ/", "v. 使惊讶", "The result astonished experts."),
  w("astronomy", "/əˈstrɒnəmi/", "n. 天文学", "She studies astronomy at college."),
  w("atlas", "/ˈætləs/", "n. 地图册", "An atlas of the whole world."),
  w("attendant", "/əˈtendənt/", "n. 服务员，随从", "A flight attendant helped us."),
  w("attorney", "/əˈtɜːni/", "n. 律师，代理人", "Hire an attorney for advice."),
  w("authentic", "/ɔːˈθentɪk/", "adj. 真实的，可靠的", "An authentic signature on it."),
  w("authoritative", "/ɔːˈθɒrətətɪv/", "adj. 权威的", "An authoritative source."),
  w("autonomy", "/ɔːˈtɒnəmi/", "n. 自治，自主", "Grant students more autonomy."),
  w("avail", "/əˈveɪl/", "v. 利用 n. 效用", "Avail yourself of this chance."),
  w("avert", "/əˈvɜːt/", "v. 避免，转移", "Avert a possible crisis."),
  w("bald", "/bɔːld/", "adj. 秃头的，光秃的", "The old man is nearly bald."),
  w("barren", "/ˈbærən/", "adj. 贫瘠的，荒芜的", "A barren hill with no trees."),
  w("besiege", "/bɪˈsiːdʒ/", "v. 围困，包围", "The city was besieged for months."),
  w("bewilder", "/bɪˈwɪldə(r)/", "v. 使迷惑", "The map bewildered the tourist."),
  w("bias", "/ˈbaɪəs/", "n. 偏见，偏向", "Avoid bias in the report."),
  w("bleak", "/bliːk/", "adj. 凄凉的，黯淡的", "A bleak future worried them."),
  w("blunder", "/ˈblʌndə(r)/", "n. 大错 v. 犯大错", "He made a costly blunder."),
  w("blunt", "/blʌnt/", "adj. 钝的，直率的", "A blunt knife and a blunt reply."),
  w("bold", "/bəʊld/", "adj. 大胆的，粗体的", "A bold plan was proposed."),
];

// 考研核心词（考研英语高频学术词汇，30 词）
const KAOYAN: WordEntry[] = [
  w("abstract", "/ˈæbstrækt/", "adj. 抽象的 n. 摘要", "An abstract concept is hard."),
  w("accelerate", "/əkˈseləreɪt/", "v. 加速，促进", "Accelerate economic growth."),
  w("accomplish", "/əˈkʌmplɪʃ/", "v. 完成，实现", "Accomplish the research task."),
  w("accurate", "/ˈækjərət/", "adj. 准确的，精确的", "Accurate data is essential."),
  w("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认，确认", "Acknowledge the limitation."),
  w("acquire", "/əˈkwaɪə(r)/", "v. 获得，习得", "Acquire academic knowledge."),
  w("adequate", "/ˈædɪkwət/", "adj. 足够的，恰当的", "Adequate preparation helps."),
  w("advocate", "/ˈædvəkeɪt/", "v. 提倡，主张", "Advocate a green policy."),
  w("allocate", "/ˈæləkeɪt/", "v. 分配，拨出", "Allocate research funding."),
  w("ambiguity", "/ˌæmbɪˈɡjuːəti/", "n. 歧义，模糊", "Remove ambiguity in writing."),
  w("arbitrary", "/ˈɑːbɪtrəri/", "adj. 任意的，武断的", "An arbitrary decision."),
  w("ascertain", "/ˌæsəˈteɪn/", "v. 查明，确定", "Ascertain the true cause."),
  w("coherent", "/kəʊˈhɪərənt/", "adj. 连贯的，清晰的", "A coherent argument."),
  w("compile", "/kəmˈpaɪl/", "v. 编纂，编译", "Compile a reference book."),
  w("compelling", "/kəmˈpelɪŋ/", "adj. 令人信服的", "A compelling reason given."),
  w("comprise", "/kəmˈpraɪz/", "v. 包含，组成", "The course comprises modules."),
  w("conceive", "/kənˈsiːv/", "v. 构想，怀孕", "Conceive a new theory."),
  w("conform", "/kənˈfɔːm/", "v. 遵守，符合", "Conform to the standard."),
  w("contradict", "/ˌkɒntrəˈdɪkt/", "v. 反驳，矛盾", "The facts contradict him."),
  w("demonstrate", "/ˈdemənstreɪt/", "v. 证明，演示", "Demonstrate the principle."),
  w("elaborate", "/ɪˈlæbərət/", "adj. 详尽的 v. 详述", "An elaborate analysis."),
  w("empirical", "/ɪmˈpɪrɪkl/", "adj. 经验主义的", "Empirical evidence matters."),
  w("facilitate", "/fəˈsɪlɪteɪt/", "v. 促进，使便利", "Facilitate the discussion."),
  w("hypothesis", "/haɪˈpɒθəsɪs/", "n. 假设", "Test a clear hypothesis."),
  w("illustrate", "/ˈɪləstreɪt/", "v. 阐明，举例", "Illustrate with examples."),
  w("implement", "/ˈɪmplɪment/", "v. 实施，执行", "Implement the strategy."),
  w("integrate", "/ˈɪntɪɡreɪt/", "v. 整合，融合", "Integrate theory with practice."),
  w("paradigm", "/ˈpærədaɪm/", "n. 范式，模范", "A new research paradigm."),
  w("propagate", "/ˈprɒpəɡeɪt/", "v. 传播，繁殖", "Propagate the findings."),
  w("validate", "/ˈvælɪdeɪt/", "v. 验证，证实", "Validate the model."),
];

// 考公速记词（公务员考试常见词汇，侧重政策行政，30 词）
const KAOGONG: WordEntry[] = [
  w("abolish", "/əˈbɒlɪʃ/", "v. 废除，废止", "Abolish the outdated policy."),
  w("abundance", "/əˈbʌndəns/", "n. 丰富，充裕", "An abundance of resources."),
  w("accelerate", "/əkˈseləreɪt/", "v. 加速，促进", "Accelerate the reform."),
  w("accommodate", "/əˈkɒmədeɪt/", "v. 容纳，适应", "Accommodate public needs."),
  w("accomplish", "/əˈkʌmplɪʃ/", "v. 完成，达成", "Accomplish the mission."),
  w("accordance", "/əˈkɔːdəns/", "n. 一致，依照", "In accordance with the law."),
  w("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累，积聚", "Accumulate work experience."),
  w("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认，确认", "Acknowledge the issue."),
  w("acquire", "/əˈkwaɪə(r)/", "v. 获得，取得", "Acquire new competence."),
  w("adequate", "/ˈædɪkwət/", "adj. 足够的，适当的", "Adequate funding required."),
  w("adhere", "/ədˈhɪə(r)/", "v. 坚持，遵守", "Adhere to the principles."),
  w("adjacent", "/əˈdʒeɪsnt/", "adj. 相邻的", "Adjacent administrative zones."),
  w("advocate", "/ˈædvəkeɪt/", "v. 提倡，拥护", "Advocate social fairness."),
  w("allocate", "/ˈæləkeɪt/", "v. 分配，配给", "Allocate the budget wisely."),
  w("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期，预见", "Anticipate potential risks."),
  w("apparent", "/əˈpærənt/", "adj. 明显的", "An apparent improvement."),
  w("assess", "/əˈses/", "v. 评估，估价", "Assess the social impact."),
  w("attribute", "/əˈtrɪbjuːt/", "v. 归因于", "Attribute success to reform."),
  w("authorize", "/ˈɔːθəraɪz/", "v. 授权，批准", "Authorize the project."),
  w("automate", "/ˈɔːtəmeɪt/", "v. 使自动化", "Automate the service."),
  w("coherent", "/kəʊˈhɪərənt/", "adj. 连贯的", "A coherent strategy."),
  w("compensate", "/ˈkɒmpenseɪt/", "v. 补偿，赔偿", "Compensate the affected."),
  w("consolidate", "/kənˈsɒlɪdeɪt/", "v. 巩固，加强", "Consolidate the gains."),
  w("constitute", "/ˈkɒnstɪtjuːt/", "v. 构成，组成", "Constitute a violation."),
  w("decree", "/dɪˈkriː/", "n. 法令 v. 颁布", "Issue a new decree."),
  w("delegate", "/ˈdelɪɡət/", "v. 委派，授权", "Delegate the duties."),
  w("formulate", "/ˈfɔːmjuleɪt/", "v. 制定，构想", "Formulate a clear plan."),
  w("implement", "/ˈɪmplɪment/", "v. 实施，执行", "Implement the policy well."),
  w("supervise", "/ˈsuːpəvaɪz/", "v. 监督，管理", "Supervise the project."),
  w("transparent", "/trænsˈpærənt/", "adj. 透明的", "A transparent process."),
];

export const WORD_BOOKS: WordBook[] = [
  {
    key: "gaokao",
    name: "高中核心词",
    scenario: "高中",
    desc: "高考 3500 词精选高频词汇，覆盖日常与基础阅读，适合高中生打牢基础。",
    words: [...GAOKAO_A, ...GAOKAO_B],
  },
  {
    key: "cet4",
    name: "四级高频词",
    scenario: "通用",
    desc: "大学英语四级考试高频基础词汇，适合日常积累与期末巩固。",
    words: CET4,
  },
  {
    key: "cet6",
    name: "六级高频词",
    scenario: "通用",
    desc: "大学英语六级较难词汇，侧重学术阅读与写作表达。",
    words: CET6,
  },
  {
    key: "kaoyan",
    name: "考研核心词",
    scenario: "考研",
    desc: "考研英语高频核心词汇，侧重学术与长难句语境。",
    words: KAOYAN,
  },
  {
    key: "kaogong",
    name: "考公速记词",
    scenario: "考公",
    desc: "公务员考试中常见词汇，侧重政策、行政与申论语境。",
    words: KAOGONG,
  },
];

export function getWordBook(key: string): WordBook | undefined {
  return WORD_BOOKS.find((b) => b.key === key);
}
